version: '3.8'
services:
  zookeeper:
    image: "confluentinc/cp-zookeeper:latest"
    container_name: zookeeper
    restart: always
    ports:
      - "22181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    healthcheck:
      test: nc -zv localhost 2181 || exit 1
      interval: 5s
      retries: 25

  redpanda-0:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda-0:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      # Address the broker advertises to clients that connect to the HTTP Proxy.
      - --advertise-pandaproxy-addr internal://redpanda-0:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      # Redpanda brokers use the RPC API to communicate with eachother internally.
      - --rpc-addr redpanda-0:33145
      - --advertise-rpc-addr redpanda-0:33145
      - --smp 1
      - --memory 1G
      - --mode dev-container
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v23.1.11
    container_name: redpanda-0
    volumes:
      - redpanda-0:/var/lib/redpanda/data
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092

  feline:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redpanda-0
    container_name: feline
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "redpanda-0:9092"
      KAFKA_SCHEMA_REGISTRY_URL: "http://redpanda-0:8081"

  kafka-client:
    image: "confluentinc/cp-kafka:latest"
    container_name: kafka-client
    command: [ "/bin/bash", "-c", "sleep infinity" ]

volumes:
  redpanda-0: {}